# Generated by Django 4.2.11 on 2024-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='age',
            field=models.IntegerField(default=2),
        ),
    ]
